version: '3.7'

services:
  autorp_ui:
   container_name: autorp_ui
   image: autorp-ui:v1
   ports:
    - '8501:8501'
   environment:
     - BACKEND_IP=autorp_backend
     - BACKEND_PORT=8080
   depends_on:
     - autorp_backend
   restart: always

  autorp_backend:
    container_name: autorp_backend
    image: autorp-backend:v1
    ports:
      - '8080:8080'
    # environment:
    #   - REDIS_IP=redis
    #   - REDIS_PORT=6379
    # depends_on:
    #   - redis
    restart: always

  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   ports:
  #     - '6379:6379'
  #   restart: always
